version: '3' 
services:

  jupyter-notebook:
    image: jontavpess/ds-jupyter-env:1.0
    hostname: jupyter
    container_name: jupyter
    #command: notebook
    #env_file:
    #  - ./data/jupyter/jupyter.env
    ports:
      - 8888:8888
    volumes:
       - ./data/notebooks:/mnt/notebooks/ #alterar
    #environment:
    #working_dir: /mnt/notebook/ #Não funcionou como o esperado
    deploy:
      resources:
        limits:
          memory: 1g
