version: '3' 
services:

  jupyter-notebook:
    image: jontavpess/ds-jupyter-env
    hostname: jupyter-notebook
    container_name: jupyter-notebook
    #command: notebook
    #env_file:
    #  - ./data/jupyter/jupyter.env
    ports:
      - 8888:8888
    volumes:
       - ./data:/mnt/data/
    #environment:
    #working_dir: /mnt/notebook/
    deploy:
      resources:
        limits:
          memory: 1g
